In [5]:
import pandas as pd 
df=pd.read_csv("flight_data_2018_to_2022.csv", sep=";" , low_memory=False )

In [2]:
df_min=df.sample(10000)

In [3]:
df_min.to_csv("sample10000.csv")

In [6]:
df_min.isna()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate
534394,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
112740,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
263818,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
62150,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
11007,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102516,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
151172,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
25098,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
72761,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False
381698,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,False

In [7]:
ratio_na=(df_min.isna().sum()/df_min.shape[0])

In [5]:
ratio_na.to_csv("ratio_na.csv")

In [8]:
columns_useful=ratio_na[ratio_na<0.5].index

In [9]:
df=df[columns_useful]

In [10]:
df.to_csv("fichier_final.csv")

In [11]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline ',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'Origin', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'Dest',
       'DestCityName', 'DestState', 'DestStateFips', 'DestStateName',
       'DestWac', 'CRSDepTime', 'DepTime', 'DepDelay', 'DepDelayMinutes',
       'DepDel15', 'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut',
       'WheelsOff', 'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrTime', 'ArrDelay',
       'ArrDelayMinutes', 'ArrDel15', 'ArrivalDelayGroups', 'ArrTimeBlk',
       'Cancelled', 'Diverted', 'CRSElapsedTime', 'ActualElapsedTime',
       'AirTime', 'Flights', 'Distance', 'DistanceGroup', 'DivAirportLandings',
       'Duplicate'],
      dtype='object')

In [63]:
df.shape

(563737, 62)

In [ ]:
import seaborn as sb
corr = df.corr()
sb.heatmap(corr, cmap="Blues", annot=True)

In [10]:
df_min=df_min.drop(columns=[])

In [50]:
df_min.to_csv("fichier_final.csv")